spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


# Application properties
admin-login: ${ADMIN_LOGIN}
admin-password: ${ADMIN_PASSWORD}

text:
  min-title-length: 3
  max-title-length: 100
  min-text-length: 3
  max-text-length: 65000